### PR TITLE
fix: Fix shift-related conversion and implement the tests

### LINKED ISSUE #20: Implement the rest of the shift intrinsic functions
The following shift intrinsic functions are not implemented yet.
- _mm_sll_epi*
- _mm_srl_epi*
- _mm_sra_epi*
- _mm_sllv_epi*
- _mm_srlv_epi*
- _mm_srav_epi*

However, the related shift intrinsic functions of **x86** and **ARM** have different behaviour when the shift value is too large .
Please check the discussion in https://github.com/DLTcollab/sse2neon/pull/17#discussion_r374810457.

### PR DESCRIPTION
**Pull request by marktwtn**
Close #20.

### CODE REVIEW

File: sse2neon.h [hunk 1]
```diff
@@ -1834,82 +1834,115 @@ FORCE_INLINE __m128i _mm_slli_epi64(__m128i a, int imm)
...
-        } else {                                                 \
-            ret = vreinterpretq_m128i_u16(                       \
-                vshrq_n_u16(vreinterpretq_u16_m128i(a), (imm))); \
-        }                                                        \
-        ret;                                                     \
+// https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_srli_epi16
+#define _mm_srli_epi16(a, imm)                                             \
+    __extension__({                                                        \
+        __m128i ret;                                                       \
+        if ((imm) == 0) {                                                  \
```
Comment (jserv) [inline sse2neon.h:1853]: How about the following changes?
```c
if ((imm) <= 0) {
    ret = a;
} else if ((imm) > 15) {
    ret = _mm_setzero_si128();
} else {
    ret = vreinterpretq_m128i_u16(vshrq_n_u16(vshlq_u16(vreinterpretq_u16_m128i(a),
         (((imm) & 15) | (((imm) & 15) == 0))));
}
```

Comment (marktwtn) [reply sse2neon.h:1853]: As I executed the `_mm_srli_epi16` on X86, it turns out that when the `imm` is less than 0 or greater than 15, the vector element would become 0.

The reason of not using `vshrq_n_u16` is that the second argument of it should be the constant immediate value.
However, the `_mm_srli_epi16` does not.
